
package client.core.gui;

import client.core.handler.ServerHandler;

/**
 * @author NouakazaPc
 */
public class GameFrame extends javax.swing.JFrame {

	private InitView initView;
	private NavigatorView navigatorView;
	private RoomView roomView;

	private ServerHandler handler;

    /**
     * Creates new form GameFrame
     */
    public GameFrame(ServerHandler handler) {
        initComponents();
	    try {
		    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			    if ("Nimbus".equals(info.getName())) {
				    javax.swing.UIManager.setLookAndFeel(info.getClassName());
				    break;
			    }
		    }
	    } catch (ClassNotFoundException
			    | InstantiationException
			    | javax.swing.UnsupportedLookAndFeelException
			    | IllegalAccessException ex) {
		    java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	    }

	    initView = new InitView(this, handler);
	    setPreferredSize(initView.getPreferredSize());
	    setContentPane(initView);
	    pack();
	    setLocationRelativeTo(null);
	    setVisible(true);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

}
