/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.core.gui;

import client.core.handler.ServerHandler;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class NavigatorView extends JPanel {

	private JButton disconnect_btn;
	private JButton enterRoom_btn;
	private JList<String> roomList_jl;

	private ServerHandler handler;

	/**
	 * Creates new form NavigatorView
	 */
	NavigatorView(ServerHandler handler) {
		this.handler = handler;
		initComponents();
		disconnect_btn.addActionListener(e -> handler.commandeDisconnect());
		enterRoom_btn.addActionListener(e -> {
			String name = roomList_jl.getSelectedValue();
			if (name != null) {
				handler.commandeEnterRoom(name.split(":")[0]);
			}
		});
		handler.commandeRoomList();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		JButton createRoom_btn = new JButton();
		enterRoom_btn = new JButton();
		JScrollPane jScrollPane1 = new JScrollPane();
		roomList_jl = new JList<>();
		disconnect_btn = new JButton();

		createRoom_btn.setText("New room");
		createRoom_btn.addActionListener(e -> {
			String roomName = JOptionPane.showInputDialog("Name of the room ");
			if (! roomName.isEmpty()) {
				handler.commandeCreateRoom(roomName);
			}
		});

		enterRoom_btn.setText("Enter room");
		enterRoom_btn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				if (roomList_jl.getSelectedValue() != null) {
					handler.commandeEnterRoom(roomList_jl.getSelectedValue());
				}
			}
		});
		jScrollPane1.setViewportView(roomList_jl);

		disconnect_btn.setText("Logout");

		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(24, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
										.addComponent(jScrollPane1)
										.addComponent(enterRoom_btn, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
										.addComponent(createRoom_btn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(disconnect_btn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(19, 19, 19))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(createRoom_btn)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 239, GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(enterRoom_btn)
								.addGap(18, 18, 18)
								.addComponent(disconnect_btn)
								.addContainerGap(55, Short.MAX_VALUE))
		);
	}// </editor-fold>//GEN-END:initComponents

	public void updateRoomsList(ArrayList<String> names, ArrayList<Integer> players, ArrayList<Integer> spectators) {
		roomList_jl.setModel(new AbstractListModel<String>() {

			public int getSize() {
				return names.size();
			}

			public String getElementAt(int i) {
				return names.get(i) + ": " + players.get(i) + " - " + spectators.get(i);
			}
		});
	}

	public void serverRefusedRoomName() {
		JOptionPane.showMessageDialog(null, "Room name is bad or already exist", "Error", JOptionPane.ERROR_MESSAGE);
	}

	public void serverRoomDoesntExist() {
		JOptionPane.showMessageDialog(null, "Sorry, room doesn't exist anymore", "Error", JOptionPane.ERROR_MESSAGE);
	}
}
