package client.core.gui;

import client.core.handler.ServerHandler;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class RoomView extends JPanel {

	private static final String SPECTATORS = "SPECTATORS ";
	private JToggleButton c0, c1, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c2;
	private JToggleButton c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c3, c30, c31;
	private JToggleButton c32, c33, c34, c35, c36, c37, c38, c39, c4, c40, c41, c42, c43;
	private JToggleButton c44, c45, c46, c47, c48, c49, c5, c50, c51, c52, c53, c54, c55, c56;
	private JToggleButton c57, c58, c59, c6, c7, c8, c9;
	private JLabel diceResult_jlb;
	private JButton dice_btn;
	private JRadioButton h00, h01, h02, h03, h10, h11, h12, h13, h20, h21, h22, h23, h30, h31, h32, h33;
	private JList<String> horseOptionList_jl;
	private JButton quit_btn;
	private JButton start_btn;
	private JLabel spectators_jlb;
	private JLabel savedp0_jlb, savedp1_jlb, savedp2_jlb, savedp3_jlb;
	private JButton moveHorse_btn;
	private JToggleButton p00, p01, p02, p03, p04, p05, p10, p11, p12, p13, p14, p15;
	private JToggleButton p20, p21, p22, p23, p24, p25, p30, p31, p32, p33, p34, p35;
	private JLabel player0_jlb, player1_jlb, player2_jlb, player3_jlb;

	private List<JToggleButton> map;
	private List<List<JRadioButton>> bases;
	private List<List<JToggleButton>> laststeps;
	private List<JLabel> endStatus;

	private List<JLabel> playersLabels;



	private ServerHandler handler;

	/**
	 * Creates new form RoomView
	 */
	RoomView(ServerHandler handler) {
		this.handler = handler;

		initComponents();
		initGame();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		c0 = new JToggleButton();
		c59 = new JToggleButton();
		c58 = new JToggleButton();
		c1 = new JToggleButton();
		c57 = new JToggleButton();
		p00 = new JToggleButton();
		c2 = new JToggleButton();
		p01 = new JToggleButton();
		c56 = new JToggleButton();
		c4 = new JToggleButton();
		c54 = new JToggleButton();
		p03 = new JToggleButton();
		c5 = new JToggleButton();
		p04 = new JToggleButton();
		c53 = new JToggleButton();
		c3 = new JToggleButton();
		p02 = new JToggleButton();
		c55 = new JToggleButton();
		p20 = new JToggleButton();
		c23 = new JToggleButton();
		c31 = new JToggleButton();
		c35 = new JToggleButton();
		c25 = new JToggleButton();
		p24 = new JToggleButton();
		p22 = new JToggleButton();
		c24 = new JToggleButton();
		c33 = new JToggleButton();
		p23 = new JToggleButton();
		c34 = new JToggleButton();
		c26 = new JToggleButton();
		c32 = new JToggleButton();
		p21 = new JToggleButton();
		c27 = new JToggleButton();
		c22 = new JToggleButton();
		p25 = new JToggleButton();
		c36 = new JToggleButton();
		c14 = new JToggleButton();
		c13 = new JToggleButton();
		c15 = new JToggleButton();
		p10 = new JToggleButton();
		c12 = new JToggleButton();
		c16 = new JToggleButton();
		p11 = new JToggleButton();
		c11 = new JToggleButton();
		c17 = new JToggleButton();
		p12 = new JToggleButton();
		c10 = new JToggleButton();
		c18 = new JToggleButton();
		p13 = new JToggleButton();
		c9 = new JToggleButton();
		c19 = new JToggleButton();
		p14 = new JToggleButton();
		c8 = new JToggleButton();
		c20 = new JToggleButton();
		c21 = new JToggleButton();
		p15 = new JToggleButton();
		c7 = new JToggleButton();
		c29 = new JToggleButton();
		c30 = new JToggleButton();
		c28 = new JToggleButton();
		p05 = new JToggleButton();
		c52 = new JToggleButton();
		c6 = new JToggleButton();
		c42 = new JToggleButton();
		c43 = new JToggleButton();
		c44 = new JToggleButton();
		c45 = new JToggleButton();
		p35 = new JToggleButton();
		c51 = new JToggleButton();
		c37 = new JToggleButton();
		p34 = new JToggleButton();
		c50 = new JToggleButton();
		c38 = new JToggleButton();
		p33 = new JToggleButton();
		c49 = new JToggleButton();
		c39 = new JToggleButton();
		p32 = new JToggleButton();
		c48 = new JToggleButton();
		c40 = new JToggleButton();
		p31 = new JToggleButton();
		c47 = new JToggleButton();
		c41 = new JToggleButton();
		p30 = new JToggleButton();
		c46 = new JToggleButton();
		JPanel player2_lt = new JPanel();
		h20 = new JRadioButton();
		h21 = new JRadioButton();
		h23 = new JRadioButton();
		h22 = new JRadioButton();
		JPanel player1_lt = new JPanel();
		h10 = new JRadioButton();
		h11 = new JRadioButton();
		h12 = new JRadioButton();
		h13 = new JRadioButton();
		JPanel player0_lt = new JPanel();
		h00 = new JRadioButton();
		h01 = new JRadioButton();
		h02 = new JRadioButton();
		h03 = new JRadioButton();
		JPanel player3_lt = new JPanel();
		h30 = new JRadioButton();
		h31 = new JRadioButton();
		h33 = new JRadioButton();
		h32 = new JRadioButton();
		player2_jlb = new JLabel();
		player1_jlb = new JLabel();
		player0_jlb = new JLabel();
		player3_jlb = new JLabel();
		dice_btn = new JButton();
		diceResult_jlb = new JLabel();
		JScrollPane jScrollPane1 = new JScrollPane();
		horseOptionList_jl = new JList<>();
		moveHorse_btn = new JButton();
		quit_btn = new JButton();
		start_btn = new JButton();
		spectators_jlb = new JLabel();
		savedp0_jlb = new JLabel();
		savedp1_jlb = new JLabel();
		savedp2_jlb = new JLabel();
		savedp3_jlb = new JLabel();

		c0.setEnabled(false);

		c59.setEnabled(false);

		c58.setEnabled(false);

		c1.setEnabled(false);

		c57.setEnabled(false);

		p00.setEnabled(false);

		c2.setEnabled(false);

		p01.setEnabled(false);

		c56.setEnabled(false);

		c4.setEnabled(false);

		c54.setEnabled(false);

		p03.setEnabled(false);

		c5.setEnabled(false);

		p04.setEnabled(false);

		c53.setEnabled(false);

		c3.setEnabled(false);

		p02.setEnabled(false);

		c55.setEnabled(false);

		p20.setEnabled(false);

		c23.setEnabled(false);

		c31.setEnabled(false);

		c35.setEnabled(false);

		c25.setEnabled(false);

		p24.setEnabled(false);

		p22.setEnabled(false);

		c24.setEnabled(false);

		c33.setEnabled(false);

		p23.setEnabled(false);

		c34.setEnabled(false);

		c26.setEnabled(false);

		c32.setEnabled(false);

		p21.setEnabled(false);

		c27.setEnabled(false);

		c22.setEnabled(false);

		p25.setEnabled(false);

		c36.setEnabled(false);

		c14.setEnabled(false);
		c14.setMargin(new java.awt.Insets(14, 2, 14, 2));
		c14.setMaximumSize(new java.awt.Dimension(9, 33));
		c14.setMinimumSize(new java.awt.Dimension(9, 33));
		c14.setPreferredSize(new java.awt.Dimension(9, 33));

		c13.setEnabled(false);
		c13.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c15.setEnabled(false);
		c15.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p10.setEnabled(false);
		p10.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c12.setEnabled(false);
		c12.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c16.setEnabled(false);
		c16.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p11.setEnabled(false);
		p11.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c11.setEnabled(false);
		c11.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c17.setEnabled(false);
		c17.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p12.setEnabled(false);
		p12.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c10.setEnabled(false);
		c10.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c18.setEnabled(false);
		c18.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p13.setEnabled(false);
		p13.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c9.setEnabled(false);
		c9.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c19.setEnabled(false);
		c19.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p14.setEnabled(false);
		p14.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c8.setEnabled(false);
		c8.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c20.setEnabled(false);
		c20.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c21.setEnabled(false);
		c21.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p15.setEnabled(false);
		p15.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c7.setEnabled(false);
		c7.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c29.setEnabled(false);

		c30.setEnabled(false);

		c28.setEnabled(false);

		p05.setEnabled(false);

		c52.setEnabled(false);

		c6.setEnabled(false);

		c42.setEnabled(false);
		c42.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c43.setEnabled(false);
		c43.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c44.setEnabled(false);
		c44.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c45.setEnabled(false);
		c45.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p35.setEnabled(false);
		p35.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c51.setEnabled(false);
		c51.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c37.setEnabled(false);
		c37.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p34.setEnabled(false);
		p34.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c50.setEnabled(false);
		c50.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c38.setEnabled(false);
		c38.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p33.setEnabled(false);
		p33.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c49.setEnabled(false);
		c49.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c39.setEnabled(false);
		c39.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p32.setEnabled(false);
		p32.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c48.setEnabled(false);
		c48.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c40.setEnabled(false);
		c40.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p31.setEnabled(false);
		p31.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c47.setEnabled(false);
		c47.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c41.setEnabled(false);
		c41.setMargin(new java.awt.Insets(14, 2, 14, 2));

		p30.setEnabled(false);
		p30.setMargin(new java.awt.Insets(14, 2, 14, 2));

		c46.setEnabled(false);
		c46.setMargin(new java.awt.Insets(14, 2, 14, 2));

		player2_lt.setBackground(new java.awt.Color(0, 0, 204));
		player2_lt.setForeground(new java.awt.Color(0, 0, 255));

		h20.setBackground(new java.awt.Color(0, 0, 204));
		h20.setEnabled(false);

		h21.setBackground(new java.awt.Color(0, 0, 204));
		h21.setEnabled(false);

		h23.setBackground(new java.awt.Color(0, 0, 204));
		h23.setEnabled(false);

		h22.setBackground(new java.awt.Color(0, 0, 204));
		h22.setEnabled(false);

		GroupLayout player2_ltLayout = new GroupLayout(player2_lt);
		player2_lt.setLayout(player2_ltLayout);
		player2_ltLayout.setHorizontalGroup(
				player2_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player2_ltLayout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(player2_ltLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
										.addComponent(h20)
										.addComponent(h22))
								.addGap(18, 18, 18)
								.addGroup(player2_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h23)
										.addComponent(h21))
								.addContainerGap(22, Short.MAX_VALUE))
		);
		player2_ltLayout.setVerticalGroup(
				player2_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player2_ltLayout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(player2_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h21)
										.addComponent(h20))
								.addGap(18, 18, 18)
								.addGroup(player2_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h23)
										.addComponent(h22))
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		player1_lt.setBackground(new java.awt.Color(255, 0, 0));
		player1_lt.setForeground(new java.awt.Color(255, 0, 0));

		h10.setBackground(new java.awt.Color(255, 0, 0));
		h10.setEnabled(false);

		h11.setBackground(new java.awt.Color(255, 0, 0));
		h11.setEnabled(false);

		h12.setBackground(new java.awt.Color(255, 0, 0));
		h12.setEnabled(false);

		h13.setBackground(new java.awt.Color(255, 0, 0));
		h13.setEnabled(false);

		GroupLayout player1_ltLayout = new GroupLayout(player1_lt);
		player1_lt.setLayout(player1_ltLayout);
		player1_ltLayout.setHorizontalGroup(
				player1_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player1_ltLayout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(player1_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(player1_ltLayout.createSequentialGroup()
												.addComponent(h12)
												.addGap(18, 18, 18)
												.addComponent(h13))
										.addGroup(player1_ltLayout.createSequentialGroup()
												.addComponent(h10)
												.addGap(18, 18, 18)
												.addComponent(h11)))
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		player1_ltLayout.setVerticalGroup(
				player1_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player1_ltLayout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(player1_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h11)
										.addComponent(h10))
								.addGap(18, 18, 18)
								.addGroup(player1_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h12)
										.addComponent(h13))
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		player0_lt.setBackground(new java.awt.Color(0, 153, 0));
		player0_lt.setForeground(new java.awt.Color(0, 153, 0));

		h00.setBackground(new java.awt.Color(0, 153, 0));
		h00.setEnabled(false);

		h01.setBackground(new java.awt.Color(0, 153, 0));
		h01.setEnabled(false);

		h02.setBackground(new java.awt.Color(0, 153, 0));
		h02.setEnabled(false);

		h03.setBackground(new java.awt.Color(0, 153, 0));
		h03.setEnabled(false);

		GroupLayout player0_ltLayout = new GroupLayout(player0_lt);
		player0_lt.setLayout(player0_ltLayout);
		player0_ltLayout.setHorizontalGroup(
				player0_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player0_ltLayout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(player0_ltLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
										.addGroup(player0_ltLayout.createSequentialGroup()
												.addComponent(h02)
												.addGap(18, 18, 18)
												.addComponent(h03))
										.addGroup(player0_ltLayout.createSequentialGroup()
												.addComponent(h00)
												.addGap(18, 18, 18)
												.addComponent(h01)))
								.addContainerGap(23, Short.MAX_VALUE))
		);
		player0_ltLayout.setVerticalGroup(
				player0_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player0_ltLayout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(player0_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h01)
										.addComponent(h00))
								.addGap(18, 18, 18)
								.addGroup(player0_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h02)
										.addComponent(h03))
								.addContainerGap(22, Short.MAX_VALUE))
		);

		player3_lt.setBackground(new java.awt.Color(255, 204, 0));
		player3_lt.setForeground(new java.awt.Color(255, 204, 0));

		h30.setBackground(new java.awt.Color(255, 204, 0));
		h30.setEnabled(false);

		h31.setBackground(new java.awt.Color(255, 204, 0));
		h31.setEnabled(false);

		h33.setBackground(new java.awt.Color(255, 204, 0));
		h33.setEnabled(false);

		h32.setBackground(new java.awt.Color(255, 204, 0));
		h32.setEnabled(false);

		GroupLayout player3_ltLayout = new GroupLayout(player3_lt);
		player3_lt.setLayout(player3_ltLayout);
		player3_ltLayout.setHorizontalGroup(
				player3_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player3_ltLayout.createSequentialGroup()
								.addGap(21, 21, 21)
								.addGroup(player3_ltLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
										.addComponent(h30)
										.addComponent(h32))
								.addGap(18, 18, 18)
								.addGroup(player3_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h33)
										.addComponent(h31))
								.addContainerGap(21, Short.MAX_VALUE))
		);
		player3_ltLayout.setVerticalGroup(
				player3_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(player3_ltLayout.createSequentialGroup()
								.addGap(21, 21, 21)
								.addGroup(player3_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h31)
										.addComponent(h30))
								.addGap(18, 18, 18)
								.addGroup(player3_ltLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(h33)
										.addComponent(h32))
								.addContainerGap(21, Short.MAX_VALUE))
		);

		String player2 = " ";
		player2_jlb.setText(player2);

		String player1 = " ";
		player1_jlb.setText(player1);

		String player0 = " ";
		player0_jlb.setText(player0);

		String player3 = " ";
		player3_jlb.setText(player3);

		dice_btn.setText("PLAY DICE");

		diceResult_jlb.setText("DICE = 0");

		jScrollPane1.setViewportView(horseOptionList_jl);

		moveHorse_btn.setText("Move horse");

		quit_btn.setText("Quit");

		start_btn.setText("Start");

		spectators_jlb.setText("Spectators : 000");

		savedp0_jlb.setForeground(new java.awt.Color(51, 153, 0));
		savedp0_jlb.setText("Green : 0");

		savedp1_jlb.setForeground(new java.awt.Color(255, 0, 0));
		savedp1_jlb.setText("Red : 0");

		savedp2_jlb.setForeground(new java.awt.Color(0, 51, 204));
		savedp2_jlb.setText("Blue : 0");

		savedp3_jlb.setForeground(new java.awt.Color(255, 204, 0));
		savedp3_jlb.setText("Yellow : 0");

		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(91, 91, 91)
												.addComponent(player1_jlb))
										.addGroup(layout.createSequentialGroup()
												.addGap(33, 33, 33)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(c14, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c13, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c15, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addComponent(p10, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c12, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c16, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addComponent(p11, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c11, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c17, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addComponent(p12, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c10, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c18, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addComponent(p13, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c9, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c19, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)))
														.addComponent(player1_lt, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(player0_lt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
																.addGap(30, 30, 30)
																.addComponent(player0_jlb)))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(p14, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c8, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c20, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(p15, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c7, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c21, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))))
								.addGap(6, 6, 6)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(c28)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(c29)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(c30)
												.addGap(90, 90, 90)
												.addComponent(player2_jlb)
												.addGap(28, 28, 28))
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c23)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p24)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(c35))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c22)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p25)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(c36)))
														.addGroup(layout.createSequentialGroup()
																.addGap(13, 13, 13)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
																		.addComponent(savedp3_jlb)
																		.addComponent(savedp0_jlb)
																		.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																				.addComponent(savedp2_jlb)
																				.addComponent(savedp1_jlb))))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c27)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p20)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c31))
														.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c26)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p21)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(c32))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c25)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p22)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(c33)))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c24)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p23)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c34))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c6)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p05)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c52))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c5)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p04)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c53))
														.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c4)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p03)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(c54))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c3)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p02)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(c55)))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c2)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p01)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c56))
														.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c1)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(p00)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(c57))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(c0)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(c59)
																		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(c58))))
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(diceResult_jlb)
																.addGap(65, 65, 65))
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup()
																				.addGap(60, 60, 60)
																				.addComponent(player2_lt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																		.addGroup(layout.createSequentialGroup()
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addComponent(p35, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c51, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c37, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addComponent(p34, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c50, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c38, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addGroup(layout.createSequentialGroup()
																								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																										.addComponent(p33, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c49, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c39, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																										.addComponent(p32, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c48, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c40, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																										.addComponent(p31, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c47, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c41, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																										.addComponent(p30, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c46, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c42, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																										.addComponent(c44, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c43, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																										.addComponent(c45, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)))
																						.addComponent(player3_lt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
																						.addGroup(layout.createSequentialGroup()
																								.addGap(22, 22, 22)
																								.addComponent(player3_jlb)))))
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup()
																				.addGap(11, 11, 11)
																				.addComponent(dice_btn)
																				.addGap(44, 44, 44))
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
																						.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																								.addComponent(moveHorse_btn)
																								.addGap(8, 8, 8))
																						.addComponent(spectators_jlb, GroupLayout.Alignment.TRAILING))
																				.addGap(33, 33, 33))))))))
						.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(start_btn)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(quit_btn)
								.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(quit_btn)
										.addComponent(start_btn))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(spectators_jlb)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(dice_btn)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(diceResult_jlb)
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(moveHorse_btn)
								.addGap(287, 287, 287))
						.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGap(57, 57, 57)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(c28, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
										.addComponent(c29, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
										.addComponent(c30, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
										.addComponent(player2_jlb)
										.addComponent(player1_jlb))
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
										.addComponent(player2_lt, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(player1_lt, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(c27, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(p20, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c31, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(c26, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c32, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(p21, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
														.addComponent(c33, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(p22, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c25, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(c24, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(p23, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c34, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))))
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(52, 52, 52)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(c19)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p13)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c9))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c20)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p14)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c8))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c17)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p11)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c11))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c18)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p12)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c10))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c16)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p10)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c12))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c21)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(p15)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addComponent(savedp3_jlb)
																		.addComponent(c7)))
														.addGroup(layout.createSequentialGroup()
																.addComponent(c15)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(c13)))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																.addComponent(c6, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																.addComponent(p05, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																.addComponent(c52, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
														.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addComponent(c5, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(p04, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c53, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addComponent(c4, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c54, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(p03, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
																						.addComponent(c55, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(p02, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c3, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																						.addComponent(c2, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(p01, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c56, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
																						.addComponent(c1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c57, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(p00, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
																						.addComponent(c58, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c59, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																						.addComponent(c0, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(player0_lt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(player0_jlb))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(player3_lt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
																				.addComponent(player3_jlb)))
																.addGap(24, 24, 24))))
										.addGroup(layout.createSequentialGroup()
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addComponent(c23, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(c35, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
														.addComponent(p24, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
																		.addComponent(c36, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(p25, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
																		.addComponent(c22, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18, 18)
																.addComponent(savedp0_jlb)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(savedp1_jlb)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(savedp2_jlb))
														.addGroup(layout.createSequentialGroup()
																.addGap(19, 19, 19)
																.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c43)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c44)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c45))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c41)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(p31)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c47))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c42)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(p30)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c46))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c39)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(p33)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c49))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c40)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(p32)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c48))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c38)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(p34)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c50))
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(c37)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(p35)
																				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(c51)))))
												.addGap(0, 0, Short.MAX_VALUE)))
								.addGap(37, 37, 37))
		);
	}// </editor-fold>//GEN-END:initComponents

	private void initGame() {

		this.map = Arrays.asList(
				c6, c0, c1, c2, c3, c4, c5, c7, c8, c9, c10, c11, c12, c13, c14, c15,
				c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29,
				c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44,
				c45, c46, c47, c48, c49, c50, c51, c53, c54, c55, c56, c57, c58, c52, p05
		);

		for (JToggleButton cas : map)
			cas.setEnabled(true);


		this.bases = new ArrayList<>();
		this.laststeps = new ArrayList<>();
		this.endStatus = Arrays.asList(savedp0_jlb, savedp1_jlb, savedp2_jlb, savedp3_jlb);

		bases.add(Arrays.asList(h00, h01, h02, h03));
		bases.add(Arrays.asList(h10, h11, h12, h13));
		bases.add(Arrays.asList(h20, h21, h22, h23));
		bases.add(Arrays.asList(h30, h31, h32, h33));

		for (List<JRadioButton> base : bases) {
			for (JRadioButton c : base) {
				c.setSelected(true);
				c.setBackground(Color.WHITE);
			}
		}

		laststeps.add(Arrays.asList(c59, p00, p01, p02, p03, p04));
		laststeps.add(Arrays.asList(p10, p11, p12, p13, p14, p15));
		laststeps.add(Arrays.asList(p20, p21, p22, p23, p24, p25));
		laststeps.add(Arrays.asList(p30, p31, p32, p33, p34, p35));

		for (List<JToggleButton> way : laststeps)
			for (JToggleButton cas : way)
				cas.setEnabled(true);

		dice_btn.setEnabled(false);
		moveHorse_btn.setEnabled(false);
		start_btn.setEnabled(false);

		playersLabels = Arrays.asList(player0_jlb, player1_jlb, player2_jlb, player3_jlb);
		playersLabels.get(0).setText(handler.getPlayerName());

		dice_btn.addActionListener(e -> handler.commandePlayDice());
		start_btn.addActionListener(e -> handler.commandeStartGame());
		quit_btn.addActionListener(e -> handler.commandeExitRoom());
		moveHorse_btn.addActionListener(e -> {
			if (horseOptionList_jl.getSelectedValue() != null) {
				handler.commandeMoveTheHorse(Integer.parseInt(horseOptionList_jl
						.getSelectedValue()
						.split(":")[1]
						.trim()));
			} else {
				handler.commandePassTurn();
			}
		});
	}

	public void severSentSpectatorsNumber(int spectators) {
		spectators_jlb.setText(SPECTATORS + spectators);
	}

	public void serverSentDiceResult(String player, int value) {
		if (handler.getPlayerName().equals(player)) {
			moveHorse_btn.setEnabled(true);
			diceResult_jlb.setText("Your DICE = " + value);
			if (value < 6) {
				int[] horses = handler.getHorses();
				ArrayList<String> hrs = new ArrayList<>();
				for (int i = 0; i < horses.length; i++)
					if (horses[i] > 0 && horses[i] <= 66)
						hrs.add("Horse : " + i);
				if (hrs.isEmpty())
					moveHorse_btn.setText("Pass my turn");
				else
					moveHorse_btn.setText("Move horse");
				horseOptionList_jl.setModel(new AbstractListModel<String>() {

					public int getSize() {
						return hrs.size();
					}

					public String getElementAt(int i) {
						return hrs.get(i);
					}
				});
			} else {
				int[] horses = handler.getHorses();
				ArrayList<String> hrs = new ArrayList<>();
				for (int i = 0; i < horses.length; i++)
					if (horses[i] <= 66)
						hrs.add("Horse : " + i);

				horseOptionList_jl.setModel(new AbstractListModel<String>() {

					public int getSize() {
						return hrs.size();
					}

					public String getElementAt(int i) {
						return hrs.get(i);
					}

				});
			}
		} else {
			diceResult_jlb.setText(player + " DICE = " + value);
			moveHorse_btn.setEnabled(false);
		}
	}

	public void severSentPlayersList(List<String> players) {
		if (players.size() >= 2)
			start_btn.setEnabled(true);
		for (int i = 0; i < playersLabels.size(); i++)
			if (i < players.size())
				playersLabels.get(i).setText(players.get(i));
			else
				playersLabels.get(i).setText(" ");
	}

	public void serverSentWinnerIs(String player) {
		JOptionPane.showMessageDialog(null, "Winner is " + player, "Winner", JOptionPane.INFORMATION_MESSAGE);
	}

	public void serverSentGameStarted() {
		start_btn.setEnabled(false);
		JOptionPane.showMessageDialog(null, "Game Started", "Game", JOptionPane.INFORMATION_MESSAGE);
	}

	public void serverSentPlayerTurn(String name) {
		diceResult_jlb.setText(name + " Turn !");
		if (name.equals("Your")) {
			dice_btn.setEnabled(true);
		} else {
			dice_btn.setEnabled(false);
		}
	}

	public void serverSentBadMove() {
		JOptionPane.showMessageDialog(null, "That move is not accepted", "Bad move", JOptionPane.WARNING_MESSAGE);
	}

	public void serverSentGameUpdate(ArrayList<String> players, ArrayList<int[]> horses) {

		cleanBoard();
		Color color = Color.white;
		for (int i = 0; i < players.size(); i++) {
			playersLabels.get(i).setText(players.get(i));
			if (i == 0)
				color = Color.GREEN;
			if (i == 1)
				color = Color.RED;
			if (i == 2)
				color = Color.BLUE;
			if (i == 3)
				color = Color.YELLOW;
			int[] h = horses.get(i);
			for (int j = 0; j < h.length; j++) {
				int xcase = ((15 * i + h[j]) % 60);
				if (h[j] == 0) {
					bases.get(i).get(j).setSelected(true);
				} else if (h[j] <= 60) {
					if (i == 0 && xcase == 0)
						xcase = 60;
					map.get(xcase - 1).setBackground(color);
				} else if (h[j] <= 66) {
					laststeps.get(i).get((h[j] - 60) - 1).setBackground(color);
				} else {
					int number = 0;
					for (int v : h)
						if (v > 66)
							number++;
					endStatus.get(i).setText(
							endStatus.get(i).getText().split(":")[0] + ": " + number
					);
				}
			}
		}
	}

	private void cleanBoard() {
		for (JToggleButton cas : map) {
			cas.setBackground(Color.WHITE);
		}
		for (List<JToggleButton> way : laststeps)
			for (JToggleButton cas : way)
				cas.setBackground(Color.WHITE);
		for (List<JRadioButton> base : bases)
			for (JRadioButton b : base)
				b.setSelected(false);
	}

	public void spectatorMode() {
		dice_btn.setEnabled(false);
		start_btn.setEnabled(false);
		moveHorse_btn.setEnabled(false);
	}
}
