image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: /bin/echo "Building"

test:
  stage: test
  script: /bin/echo "Testing" 

deploy:
  stage: deploy
  script: /bin/echo "Deploying"