image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn install -B
  
test:
  stage: test
  script:
    - /bin/echo "here we will test the server and the client later seperatly"

deploy :
  stage: deploy
  script:
    - /bin/echo "here we will test the server and the client together"